# Generated by Django 4.0.4 on 2023-10-19 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_history',
            name='universit_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartadvisor.university_courses'),
        ),
    ]
