# Generated by Django 4.0.4 on 2023-10-19 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartadvisor', '0002_course_history_universit_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_history',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartadvisor.course'),
        ),
    ]
